### ISSUE TITLE
Генерирование пароля без нажатия на кнопку

### ISSUE THREAD

**Issue by ExEr7um** [Iskait/password-generator#1]
Это я - твой единственный пользователь. Я на протяжении многих лет создавал иллюзию того, что твоим генератором паролей пользуются много людей, но это был я. Сейчас напишу это сообщение со всех аккаунтов.

Так вот я устал на кнопку жать, сделай чтоб автоматически генерировалось.

**Comment by memew1se** [comment]
Это я - твой единственный пользователь. Я на протяжении многих лет создавал иллюзию того, что твоим генератором паролей пользуются много людей, но это был я. Сейчас напишу это сообщение со всех аккаунтов.

Так вот я устал на кнопку жать, сделай чтоб автоматически генерировалось.
